// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Movies.Application.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.Property<Guid>("GenresId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MoviesId")
                        .HasColumnType("uuid");

                    b.HasKey("GenresId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("MovieGenres", (string)null);
                });

            modelBuilder.Entity("Movies.Application.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2f54e31-f790-4192-85ad-21ce154b2731"),
                            Title = "Action"
                        },
                        new
                        {
                            Id = new Guid("78dd3d3a-361d-4e7c-91ac-df0b6cbdbbd7"),
                            Title = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("d72c8397-de4c-4a48-bc5d-02fd87d72f6e"),
                            Title = "Animation"
                        },
                        new
                        {
                            Id = new Guid("edc4e41b-39ee-4162-a650-faa8022938a1"),
                            Title = "Biography"
                        },
                        new
                        {
                            Id = new Guid("6742e068-7729-465a-befe-6d3e76efa9fc"),
                            Title = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("e913cfee-92a8-4586-9e49-9cd7af8d71b6"),
                            Title = "Crime"
                        },
                        new
                        {
                            Id = new Guid("10d1b4cf-732e-47f4-a548-60bbeee9aeb4"),
                            Title = "Documentary"
                        },
                        new
                        {
                            Id = new Guid("f86cb42e-3a99-4238-be25-72fec73afd18"),
                            Title = "Drama"
                        },
                        new
                        {
                            Id = new Guid("03b6508c-e52a-48e7-a9f4-f7dee2b311f1"),
                            Title = "Family"
                        },
                        new
                        {
                            Id = new Guid("e1452955-8ad1-422b-b3ac-04a7eb2c8595"),
                            Title = "Fantasy"
                        },
                        new
                        {
                            Id = new Guid("a3056e90-e607-4d80-b79a-be4a303fb750"),
                            Title = "History"
                        },
                        new
                        {
                            Id = new Guid("8a1705a0-c107-42b3-a4b6-ff7af8971d04"),
                            Title = "Horror"
                        },
                        new
                        {
                            Id = new Guid("4d05fb9f-a205-4b16-a1c5-fd0e198652f5"),
                            Title = "Musical"
                        },
                        new
                        {
                            Id = new Guid("c0b896ec-9d08-4e37-8319-7408d946635e"),
                            Title = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("9fc1f505-aa85-49c2-ae4e-f2616b47f294"),
                            Title = "Romance"
                        },
                        new
                        {
                            Id = new Guid("4c4ccd31-16b4-4922-b0ed-f5481bd813f7"),
                            Title = "Sci-Fi"
                        },
                        new
                        {
                            Id = new Guid("c249776f-64a6-44c5-9780-24bd5222094e"),
                            Title = "Sport"
                        },
                        new
                        {
                            Id = new Guid("9ceed180-37b2-4de7-be74-baf0675100ad"),
                            Title = "War"
                        },
                        new
                        {
                            Id = new Guid("80a1db55-0d24-4eb5-a5d5-27361bcb6039"),
                            Title = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("a4254d6b-7e05-4834-ba64-1f0aab18baca"),
                            Title = "Western"
                        });
                });

            modelBuilder.Entity("Movies.Application.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("YearOfRelease")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.HasOne("Movies.Application.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Application.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
